name: CI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    
env:
  DOCKER_ID: ${{secrets.DOCKER_ID}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: menu-api-express-ts
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run yarn
        run: yarn
      - name: Docker login
        run: docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
        
