name: Test CI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
env:
  DOCKER_USERNAME: jaoearn
  DOCKER_PASSWORD: Jaoearn_docker.hub
  REPO_NAME: menu-api-express-ts
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run yarn
        run: yarn
  docker-login:
    needs:  build
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2 
      - name: docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
 
