name: Test CI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: Jaoearn_docker.hub
  REPO_NAME: menu-api-express-ts
  
jobs:
  docker-login:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2 
      - name: docker login
        run: echo ${{secrets.DOCKER_USERNAME}} 
 
